// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLnhom07.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231017020928_Create_Table_HoaDon")]
    partial class Create_Table_HoaDon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("BTLnhom07.Models.HoaDon", b =>
                {
                    b.Property<string>("HoaDonCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoaDonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SanPhamCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoLuong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HoaDonCode");

                    b.ToTable("HoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
